fac/serverless-tools

.rubocop.yml, functions.yml, lib/deployer.rb
I've added the same rubocop file as the event system module, and I've fixed the errors which were present when running rubocop.
=> Reduce cognitive complexity of deployer.rb

Gemfile.lock, serverless-tools.gemspec
Resolve the security issue: https://github.com/fac/serverless-tools/security/dependabot/serverless-tools.gemspec/bundler/open
=> Update bundler dependency

Gemfile.lock, lib/serverless-tools/deployer/python_builder.rb, lib/serverless-tools/version.rb, pyproject.toml, test/deployer/python_builder_test.rb
Rename build package to lambda-package to avoid conflicts with terraform package.
=> Rename build package to lambda-package

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
https://github.com/fac/data-platform/issues/770
=> Use container from GHCR in action.yml

.github/workflows/push-to-ghcr.yml, README.md
• adds an initial "v" to the container version name
• updates README with contributing instructions
=> Fix container version name & update README

Gemfile.lock, lib/serverless-tools/version.rb
Update version ahead of GH release
=> Prepare for v0.12.2

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Bumping version to include dependency updates:
- #122
- #123
- #114
-  #117
=> Bumping serverless tools version: 0.13.3

Gemfile.lock, README.md, action.yml, lib/serverless-tools/version.rb
=> Release the dependabot bumps

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing `0.14.5`:
- #143
- #145
=> Bump serverless-tools to 0.14.5

Gemfile.lock, README.md, action.yml, lib/serverless-tools/version.rb
Releasing these changes:
* #175
* #177
* #178
* #179
=> Bump serverless-tools to 0.14.12

.github/workflows/create-gem-bump-branch.yml
Automate this section of the README.
Planning to run this as a workflow dispatch to save donkey work (and because setting up Ruby 2.7.0 on an M1 mac is a pain...)
=> Automate version bumping

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
- https://github.com/fac/serverless-tools/pull/211
- https://github.com/fac/serverless-tools/pull/212
- https://github.com/fac/serverless-tools/pull/213
- https://github.com/fac/serverless-tools/pull/214
Dev-P Ticket:
- https://github.com/fac/dev-platform/issues/1872
=> Bumping Gem Version

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Bump octokit from 7.2.0 to 8.0.0
Bump AWS gems
=> Bump serverless-tools to 0.17.0

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing:
* #228
* #229
* #230
* #231
* #232
* #233
=> Bump serverless-tools to 0.17.3

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Bumping the version after dependency bumps:
- #238
- #239
=> Bumping serverless tools version

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Publishing these changes:
* #241
* #242
=> Bump serverless-tools to 0.17.5

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.17.6

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Bumping version for dependency update:
- https://github.com/fac/serverless-tools/pull/248
=> Bumping version

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.17.8

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing:
- https://github.com/fac/serverless-tools/pull/258
=> Bumping serverless-tools version

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.17.15

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing:
- #305
- #306
Dev-P Ticket:
- https://github.com/fac/dev-platform/issues/2283
=> Updating serverless tools version

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing:
* #340
* #341 
* #342
* #343
=> Bump serverless-tools to 0.17.23

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Reverting Ruby version bump
- #370
=> Bump serverless-tools to 0.18.1

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing:
* #372
* #373 
* #374
=> Bump serverless-tools to 0.18.2

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.18.3

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.18.4

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Bumping dependencies:
- #385
- #386
=> Bump serverless-tools to 0.18.5

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.18.6

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.19.11

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
=> Bump serverless-tools to 0.19.12

Gemfile.lock, action.yml, lib/serverless-tools/version.rb
Releasing:
- #447
- #448
- #449
=> Bump serverless-tools to 0.19.15
