.rubocop.yml
Gemfile.lock
lib/serverless-tools/cli.rb
lib/serverless-tools/comment.rb
lib/serverless-tools/deployer/aws_lambda_config.rb
lib/serverless-tools/deployer/aws_lambda_function.rb
lib/serverless-tools/git.rb
lib/serverless-tools/version.rb
serverless-tools.gemspec
test/comment_test.rb
test/deployer/aws_lambda_config_test.rb
test/deployer/aws_lambda_function_test.rb
test/deployer/deployer_test.rb
test/git_test.rb

Removes the use of GITHUB_SHA which caused issues depending on which Github Workflow trigger (push vs issue_comment). The comment and deployer now use a shared code path and we'll now output the S3 key to help spot when the sha's aren't aligning easier.
There's another follow-up to potentially make the comment format nicer _and_ pull the lambda config to check wait until the status is either `Successful` or `Failed` but they are separate issues/enhancements.

Fix deploy action

---

Gemfile.lock
lib/serverless-tools/deployer/python_builder.rb
lib/serverless-tools/version.rb
pyproject.toml

Fix docker image python errors causing the python bundles not being built correctly and bump gem version to 0.4.3.

Fix docker image python errors and bump gem version

---

Gemfile.lock
lib/serverless-tools/cli.rb
lib/serverless-tools/deployer.rb
lib/serverless-tools/deployer/ecr_pusher.rb
lib/serverless-tools/deployer/function_deployer.rb
lib/serverless-tools/deployer/options.rb
lib/serverless-tools/deployer/overrides.rb
lib/serverless-tools/deployer/s3_pusher.rb
lib/serverless-tools/version.rb
serverless-tools.gemspec
test/deployer/ecr_pusher_test.rb
test/deployer/function_deployer_test.rb
test/deployer/overrides_test.rb
test/deployer/s3_pusher_test.rb
test/deployer_test.rb

This behaviour is 'dangerous' as it overwrites the previous
deployments code. But is useful for development when iterating
where you may not want to commit your changes.
Also relies on the Thor CLI defaults to populate the overrides
to allow us to handle less.
closes https://github.com/fac/serverless-tools/issues/12

Enables forcing a deployment without a new commit.

---

Dockerfile
Gemfile.lock
README.md
lib/serverless-tools/deployer/function_deployer.rb
lib/serverless-tools/deployer/lambda_updater.rb
lib/serverless-tools/version.rb
test/deployer/function_deployer_test.rb
test/deployer/lambda_updater_test.rb

Closes #10 and Closes #11
The idea here is that when the CLI is ran from a 'local' device, we don't get the output required for Github Actions. The local output then gives nicer feedback when the actions are performed. As a result, we will also wait until the lambda status has 'settled' into a positive state, or raises an error if it fails to update. If an error is raised, the failure message is logged by the Function Deployer. 
As a side note, we raise where the logging is managed, so the individual lambda updater no longer worries about logging. The benefit here is that it does not care if it's running in a github action. The centeralised 'deployer' class (Function Deployer) will manage all the logging.

Ux improvements

---

.github/workflows/freeagent-gem.yml
serverless-tools.gemspec

This PR follow the steps outlined in notion to add this gem to our internal gems: https://www.notion.so/freeagent/GitHub-Actions-Creating-Workflows-0a65b05b8cf94ebda71ad203e04e96df#22df312d771e4996bf140255b4eb9a09
This will allow others to install the gem like other gems (and not have to clone the repo and install it locally).

Add Workflow for publishing gem to FAC Gem repo

---

Gemfile.lock
lib/serverless-tools/cli.rb
lib/serverless-tools/deployer/function_deployer.rb
lib/serverless-tools/version.rb
test/deployer/function_deployer_test.rb

- Updating the serverless tool to output the new `set-output` syntax, since the old one will be deprecated
Before:
```
echo "::set-output name=output_var::$output_string"
```
After:
```
echo "output_var=$output_string" >> "$GITHUB_OUTPUT"
```
Dev-P ticket:
- https://github.com/fac/dev-platform/issues/1271

Fix `set-output` in serverless-tool repo

---

Gemfile.lock
lib/serverless-tools/cli.rb
lib/serverless-tools/comment.rb
lib/serverless-tools/version.rb
test/comment_test.rb

The change to use `$GITHUB_OUTPUT` instead of the deprecated `set-output` broke the formatting of multi-line comments: 
It looks like the `$GITHUB_OUTPUT` [interprets multi-line values differently than `set-output`](https://stackoverflow.com/questions/74137120/how-to-fix-or-avoid-error-unable-to-process-file-command-output-successfully)
This PR changes the behaviour of the `comment` command to insert lines individually into the `$GITHUB_OUTPUT` env variable. The resulting comment looks as follows: 
Tested on[ this branch](https://github.com/fac/event-system/pull/163) in the event-system repo.

Fix multi-line comments for function updates

---

README.md

This solves the error:
```
expected params[:registry_id] to be a String, got value *** (class: Integer) instead.
```

Quote registry_id in container example

---

Dockerfile
Gemfile.lock
lib/serverless-tools/version.rb

This updates the Dockerfile to ensure that we always install the correct version of Bundler for the Gemfile.lock before attempting to `bundle install`. This will fix issues where the `ruby:2.7-slim-bullseye` base image (that is used by the Lambda template) has an older version of `bundle` than the lockfile - causing a failure.
I got the line to fix this from the [bundler blog](https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html). We should be [okay after bundler 2.3](https://bundler.io/blog/2022/01/23/bundler-v2-3.html) as it will auto-install the correct version for us.
I've tested this internally and the image successfully builds on the `ruby:2.7-slim-bullseye` base image.

Always Install Correct Bundler Version

---

Dockerfile
Gemfile.lock
README.md
lib/serverless-tools/deployer/ecr_pusher.rb
lib/serverless-tools/version.rb
test/deployer/ecr_pusher_test.rb

closes https://github.com/fac/serverless-tools/issues/27
Docker support has always been limited to running serverless tools locally. This change updates the Dockerfile (which can be used locally) or more commonly as a Github Action. The image now supports building and pushing Docker based functions, as well as the other runtimes (Python 3.9, Ruby2.7).
This super seeds #64 and is less disruptive to downstream users.
Example of running build and deploy for a Docker based image: https://github.com/fac/data-lake-etl-python/actions/runs/3583315003/jobs/6028599518

Enable building and pushing Docker based functions from within Docker (and GHA)

---

Gemfile.lock
lib/serverless-tools/notifier/deployment_status_message.rb
lib/serverless-tools/version.rb
test/notifier/deployment_status_message_test.rb

* get the branch name from the `head_branch` attribute
* get the PR number from the run's display title if otherwise missing
* get the commit message from the `head commit`

Fix notifier for prod deployments

---

Gemfile.lock
lib/serverless-tools/deployer/lambda_updater.rb
lib/serverless-tools/version.rb
test/deployer/lambda_updater_test.rb

30 seconds is quite low, we may as well wait for 2 minutes before
deciding something's gone wrong.
The main thing to go wrong at the Lambda update stage would be missing
permissions so generally only when initially setting up, after things
are set up there's minimal benefit to having a low timeout.
This could be configurable but I'd still be more forgiving as a default
value to avoid confusion on someone hitting this as soon as they start
using serverless-tools and getting confused (I'm talking from experience
here).

Increase timeout for Lambda to update

---

.github/workflows/freeagent-gem.yml
.github/workflows/push-to-ghcr.yml
Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Since events triggered by the GITHUB_TOKEN don’t trigger other workflows,
the "Push to Github Container Registry" workflow currently isn't being
triggered when a new version tag is pushed to the repository once the gem
gets released. Instead, we can trigger the workflow explicitly.
https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

Trigger the GHCR push workflow from freeagent-gem.yml 

---

Gemfile.lock
lib/serverless-tools/version.rb

Release the various AWS and Rubocop gem upgrades from the last month
* [Bump aws-sdk-s3 from 1.119.0 to 1.119.1](https://github.com/fac/serverless-tools/commit/9d2ba193a764acedc8cc2cdf14456065b45f1dfc)
* [Bump rubocop from 1.44.1 to 1.45.1](https://github.com/fac/serverless-tools/commit/430fcbdab2600922158f4522bad71fa58af2a5b0)
* [Bump aws-sdk-s3 from 1.118.0 to 1.119.0](https://github.com/fac/serverless-tools/commit/115054c96fafa76b51c8245bb7b1a90d4a078ac1)
* [Bump aws-sdk-lambda from 1.90.0 to 1.91.0](https://github.com/fac/serverless-tools/commit/5ab66cfab5e5eb5add9c06765d30a5d6ba1f3431)
* [Bump rubocop from 1.43.0 to 1.44.1](https://github.com/fac/serverless-tools/commit/a3d50bd997daa859e88918c7f5774d731223c20f)
* [Bump aws-sdk-ecr from 1.57.0 to …

Bump serverless-tools to 0.12.3

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

In the previous PR I forgot to bump the version up in the action.yml so I'm doing that here. There's a little risk in that the previous few versions haven't been rolled out but people _think_ they've been updating to the latest version. In almost all previous versions the changes have been gem updates.

Release v0.13.1

---

Gemfile.lock
README.md
action.yml
entrypoint.sh
lib/serverless-tools/version.rb

The following changes are required to resolve https://github.com/fac/serverless-tools/issues/120
Ultimately, the issue stems from an updated git client containing a security fix to prevent prevent parent directories manipulating child directories owned by others. As Serverless Tools runs in a container on Github Runners with different owners, we were unable to use the Git Client.
The fix for this is to specify that the directory is safe. For more information see the issues, and linked issues within.
Examples of using the changes:
https://github.com/fac/data-lake-etl-python/actions/runs/4677070104/jobs/8284231859
Examples of prior failing runs using the previous version:
https://github.com/fac/data-lake-etl-python/actions/runs/4668315202/jobs/8283232437

Fix git client CVE-2022-24765 updates

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Releasing 0.13.4:
- #125
- #126
- Feature - Provides support for "Snow" Storage class.
- #127
- Feature - Add Python 3.10 (python3.10) support to AWS Lambda

Bumping serverless tools version: 0.13.4

---

Gemfile.lock
README.md
action.yml
lib/serverless-tools/notifier/deployment_status_message.rb
lib/serverless-tools/version.rb
test/notifier/deployment_status_message_test.rb

This PR implements a handful of improvements to how Slack deployment notifications get built in the Notifier tool: 
• **Problem**: tagging Slack users doesn't work if the person's Github name is formatted in an usual way (e.g. using PascalCase or including numbers)
**Solution**: We're now stripping any numbers, and split the Github username on uppercase letters. 
• **Problem:** Slack notifications fail to be built if the PR number is missing from the workflow run's `display_title` (https://github.com/fac/serverless-tools/issues/107)
**Description:** When a PR is merged, the Github workflow run's information doesn't reference the PR directly (as it does, e.g. when pushing to the repository), but the PR number _should_ be included in the PR title. At present, we're trying to retrieve the PR …

Improve the deployment message published by the Notifier tool

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependency updates
- Bump test-unit from 3.5.7 to 3.5.8 #135
- Bump rubocop from 1.50.2 to 1.51.0 #134
- Bump thor from 1.2.1 to 1.2.2 #133
- Bump mocha from 1.16.0 to 1.16.1 #111

Bump serverless-tools to 0.14.2

---

Gemfile.lock
README.md
serverless-tools.gemspec

I like it when reading a list of things to to, if the list includes the command I should run. It's easier to remember when coming back to a process I don't use that often!
I also added the `gem-release` gem, which knows how to update `version.rb` for gems.

Update release docs to include commands to run

---

.github/workflows/reviewdog.yml

Previously we added `actionlint` workflows to lots of repos:
- https://github.com/fac/dev-platform/issues/314
They trigger on every push to a PR branch, so most of the time this is unnecessary, as workflows are rarely updated. Really we only need to trigger `actionlint` when workflows are changed.
We're now looking to use org-wide reusable workflows that can be updated in one central place.
The org-wide shared workflow is for private repos only. We're using `fac/hermod` as the public mirror for the private workflow since only a few repos are public and require this workflow. In future we might look to create a `shared-workflows-public` repo if necessary.
Dev-P ticket
- https://github.com/fac/dev-platform/issues/1002

Use org-wide reusable workflow for actionlint

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependency Updates
- https://github.com/fac/serverless-tools/pull/158
- https://github.com/fac/serverless-tools/pull/157
- https://github.com/fac/serverless-tools/pull/152

Bump serverless-tools to 0.14.7

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependency bumps
- Bump rubocop from 1.53.0 to 1.54.1 serverless-tools#166
- Bump the aws-dependencies group with 3 updates serverless-tools#165

Bump serverless-tools to 0.14.8

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

* Depedency Updates
* aws-sdk-lambda from 1.101.0 to 1.102.0
* aws-sdk-s3 from 1.127.0 to 1.128.0
* aws-sdk-ecr from 1.61.0 to 1.62.0

Bump serverless-tools to 0.14.9

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependency bumps
* Bump rubocop from 1.54.1 to 1.54.2 serverless-tools#171
* Bump the aws-dependencies group with 3 updates serverless-tools#170

Bump serverless-tools to 0.14.10

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Releasing AWS dependabot updates:
- https://github.com/fac/serverless-tools/pull/173

Bump serverless-tools to 0.14.11

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Minor aws-dependencies and rubocop bumps:
https://github.com/fac/serverless-tools/pull/184
https://github.com/fac/serverless-tools/pull/183

Patch gem bump - singhprd

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Bump Dependancies
* https://github.com/fac/serverless-tools/pull/195
* https://github.com/fac/serverless-tools/pull/194
* https://github.com/fac/serverless-tools/pull/192

Bump serverless-tools to 0.14.14

---

Gemfile.lock
action.yml
lib/serverless-tools/deployer/ecr_pusher.rb
lib/serverless-tools/logging.rb
lib/serverless-tools/version.rb
test/deployer/ecr_pusher_test.rb

We have had occassions when deploying when an image can not be found in ECR. However, when we deploy, we expect the image to be there. There are a number of reasons why this could be. We're adding the logging to test what the response is from ECR, and what tag we're trying to use. This should help narrow down the issue.
Example of usage (in runner): https://github.com/fac/data-lake-management/actions/runs/6199076798/job/16831244023
Example of usage (in workflow.yml):
```yml
- name: Push Assets to ECR
uses: fac/serverless-tools@add-logging-for-pushing-images
with:
command: deploy push data-lake-management_matillion_job_listener_v1
env:
SERVERLESS_TOOLS_LOG_LEVEL: "debug"
```

Add logging for when an image can't be found in ECR.

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependency bumps
* https://github.com/fac/serverless-tools/pull/209
* https://github.com/fac/serverless-tools/pull/208
* https://github.com/fac/serverless-tools/pull/207

Bump serverless-tools to 0.14.18

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Version bumps have been missed for a few weeks, so this will likely have [a few more dependency bumps](https://github.com/fac/serverless-tools/compare/v0.17.11...main) than normal.

Bumping version number

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependency Updates
[Bump the aws-dependencies group across 1 directory with 3 updates](https://github.com/fac/serverless-tools/commit/bfad4ad3f95b1d3838fe446efd240546583f8e2b)
[Bump octokit from 8.1.0 to 9.1.0](https://github.com/fac/serverless-tools/commit/474a6e6c3ae2a0250cfeedfab5325e3704a66ec6)
[Bump mocha from 2.3.0 to 2.4.0](https://github.com/fac/serverless-tools/commit/f5956c097698ac21a33251cb56c4acc39d29a538)

Release v0.17.13

---

README.md

The gem release step expects to create a tag for the new gem version. Manually doing the Release Notes and creating a tag before this action has completed will cause the release workflow to fail at the gem release step. This causes the docker image step to be skipped, resulting in:
- dependabot being aware of a new release
- the gem version being available
- no docker imaage for the release being available.
Dev-P are a bit strapped for time just now, so I'm documenting our way around the issue for now.
Dev-P Ticket:
- https://github.com/fac/dev-platform/issues/2283

Updating release guidance

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Resolving versioning issues:
- [v0.17.19](https://github.com/fac/serverless-tools/releases/tag/v0.17.19) was incorrectly released (no version bump, but created in GitHub Releases)
- [v0.17.20](https://github.com/fac/serverless-tools/releases/tag/v0.17.20) had it's version bumped but incorrectly to `v0.17.19`, marked correctly in GitHub Releases
Making a clean break here to release `v0.17.21` both as version and as GitHub Release

Bumping to v0.17.21

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Bumping serverless-tools version:
- Updated Ruby version `3.4.1`
- Dependabot PRs

Bump serverless-tools to 0.18.0

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Releasing `0.19.0` after some dependency updates.
> [!WARNING]  
> Octokit has removed some deprecated commands:
> - https://github.com/octokit/octokit.rb/pull/1720

Bump serverless-tools to 0.19.0

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

- https://github.com/fac/serverless-tools/pull/397
- https://github.com/fac/serverless-tools/pull/398

Bump serverless-tools to 0.19.1

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Bump serverless-tools to 0.19.4

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Dependencies
- https://github.com/fac/serverless-tools/pull/408
- https://github.com/fac/serverless-tools/pull/409
- https://github.com/fac/serverless-tools/pull/410

Bump serverless-tools to 0.19.5

---

Gemfile.lock
action.yml
lib/serverless-tools/version.rb

Bump serverless-tools to 0.19.14
